### ISSUE TITLE
[1-channel-board] Directly connect R207 and R211

### ISSUE THREAD

**Issue by gabrielbrunheira** [cnpem-sei/qds-cv-hw#10]
Instead of using the GND-ISO plane to connect pads of R207 and R211, use a track, similar to the one used between R205 and R207, to keep differential path more symmetrical:

![R2070-R211](https://user-images.githubusercontent.com/16702368/232783834-140852bb-170d-400a-a2b4-a1047922abdc.png)

**Comment by samufraga** [comment]
Solved in 345a3004f5c66c8f06bebcbef8cb4dfca73e6ad4 commit.
