### ISSUE TITLE
[1-channel-board] Move test-points away from tracks

### ISSUE THREAD

**Issue by gabrielbrunheira** [cnpem-sei/qds-cv-hw#11]
It's not recommended to use test-point pads in the middle of tracks, such as this:

![14V-test-points](https://user-images.githubusercontent.com/16702368/232784591-6776ef64-33ac-4300-ba07-2966f0df4f04.png)

**Comment by samufraga** [comment]
Solved in 345a3004f5c66c8f06bebcbef8cb4dfca73e6ad4 commit.
