### ISSUE TITLE
[main/1-channel-board] Feed protection relay coil with +15V

### ISSUE THREAD

**Issue by gabrielbrunheira** [cnpem-sei/qds-cv-hw#12]
Now it's using the +14V provided by the LDO regulator, which should be more dedicated for the sensitive analog circuits.

![relay-coil-14V](https://user-images.githubusercontent.com/16702368/232786116-78cafc12-96c2-4d01-88e3-e79909dffe00.png)

**Comment by samufraga** [comment]
Solved in 345a3004f5c66c8f06bebcbef8cb4dfca73e6ad4 commit.
