### ISSUE TITLE
[1-channel-board] Place Earth vias next to U201

### ISSUE THREAD

**Issue by gabrielbrunheira** [cnpem-sei/qds-cv-hw#15]
Place vias to Earth in the positions marked below to improve current flow from the output of U201A to the Earth:

![U201-earth-vias](https://user-images.githubusercontent.com/16702368/232797503-e4b6d657-2520-439f-967d-7fd6b07b79ce.png)

**Comment by samufraga** [comment]
Solved in 345a3004f5c66c8f06bebcbef8cb4dfca73e6ad4 commit.
