### ISSUE TITLE
[1-channel-board] Move via to improve Earth path on Top layer

### ISSUE THREAD

**Issue by gabrielbrunheira** [cnpem-sei/qds-cv-hw#16]
Track from this net is blocking Earth plane on Top Layer. Moving this via to the left will reduce current path:

![image](https://user-images.githubusercontent.com/16702368/232798609-05db6799-83a1-4a18-a280-675e34d95c66.png)

**Comment by samufraga** [comment]
Solved in 345a3004f5c66c8f06bebcbef8cb4dfca73e6ad4 commit.
