### ISSUE TITLE
Replace 74574 flip-flop with 74573 latch to allow protection during reset

### ISSUE THREAD

**Issue by gabrielbrunheira** [cnpem-sei/qds-cv-hw#48]
Tests with the 1-channel prototype showed that protection is blocked while reset button is pressed. Simulation and tests showed that replacing the 74HC574 flip-flop (U702) with a 74HC573 latch solve this problem. 

Remember to update schematics on both branches/releases.

**Comment by samufraga** [comment]
Commit dad628a solved this issue for main branch.
